/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cde.tela;

import cde.connection.MyConnection;
import cde.persistencia.bd.ComponentDao;
import cde.persistencia.bd.TypeDao;
import cde.persistencia.excel.Excel;
import cde.persistencia.txt.FileTxt;
import cde.util.ConvertDateToStringUtil;
import cde.util.RandomIdUtil;
import cde.vo.ComponentVo;
import cde.vo.TypeVo;
import com.mysql.jdbc.Connection;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lukas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    List<ComponentVo> components;
    List<TypeVo> types;
    ComponentVo component;
    TypeVo type;
    ComponentDao cDao;
    TypeDao tDao;
    public TelaPrincipal() {
        initComponents();
        btnExcel.setEnabled(false);
        btnSalvarBd.setEnabled(false);
        btnSalvarTxt.setEnabled(false);
        int codigo = (int) RandomIdUtil.generateRandomId(000000, 999999);
        txComponent.setText(Integer.toString(codigo));
        try{
            types = tDao.carregaDados();
        } catch(Exception e){
            e.getMessage();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRdGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txCompName = new javax.swing.JTextField();
        cbType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txCompMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txCompSn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txCompModel = new javax.swing.JTextField();
        rdExcel = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rdBd = new javax.swing.JRadioButton();
        btnExcel = new javax.swing.JButton();
        btnSalvarBd = new javax.swing.JButton();
        txFilePath = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txComponent = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txPrice = new javax.swing.JTextField();
        rdTxT = new javax.swing.JRadioButton();
        btnSalvarTxt = new javax.swing.JButton();
        btTelaDados = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de componentes");

        jLabel2.setText("Nome");

        cbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbType.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbTypeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel3.setText("Tipo");

        jLabel4.setText("Marca");

        jLabel5.setText("Nº Serial");

        jLabel6.setText("Modelo");

        btnRdGroup.add(rdExcel);
        rdExcel.setText("Excel");
        rdExcel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdExcelStateChanged(evt);
            }
        });

        jLabel7.setText("Como deseja salvar os dados?");

        btnRdGroup.add(rdBd);
        rdBd.setText("Banco de dados");
        rdBd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdBdStateChanged(evt);
            }
        });

        btnExcel.setText("Gerar Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        btnSalvarBd.setText("Salvar");
        btnSalvarBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarBdActionPerformed(evt);
            }
        });

        jLabel9.setText("Pasta Padrão");

        jLabel8.setText("Código Componente");

        txComponent.setEditable(false);

        jLabel10.setText("Preço:");

        btnRdGroup.add(rdTxT);
        rdTxT.setText("Arquivo .txt");
        rdTxT.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdTxTStateChanged(evt);
            }
        });

        btnSalvarTxt.setText("Salvar em  .txt");
        btnSalvarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTxtActionPerformed(evt);
            }
        });

        btTelaDados.setText("Ver Dados");
        btTelaDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTelaDadosActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txCompMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(txCompModel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(cbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txCompSn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rdExcel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(rdBd)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnSalvarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                .addComponent(btnSalvarBd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(rdTxT))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btTelaDados, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txComponent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txCompName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addComponent(txFilePath)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCompName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txComponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCompMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCompModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCompSn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdExcel)
                    .addComponent(btnExcel))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdTxT)
                    .addComponent(btnSalvarTxt)
                    .addComponent(btTelaDados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBd)
                    .addComponent(btnSalvarBd)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdExcelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdExcelStateChanged

        if(this.rdExcel.isSelected()){
            txFilePath.setText(returnPath(".xls"));
            btnExcel.setEnabled(true);
        } else {
            txFilePath.setText("");
            btnExcel.setEnabled(false);
        }
    }//GEN-LAST:event_rdExcelStateChanged

    private void rdBdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdBdStateChanged
        if(this.rdBd.isSelected()){
            btnSalvarBd.setEnabled(true);
            txFilePath.setEnabled(false);
        } else {
            btnSalvarBd.setEnabled(false);
            txFilePath.setEnabled(true);
        }
    }//GEN-LAST:event_rdBdStateChanged

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        String path = txFilePath.getText();
        List<ComponentVo> components = new ArrayList<>();
        
        Excel exc = new Excel(path);
        ComponentVo vo;
        /*vo = new ComponentVo(
                Integer.parseInt(txComponent.getText()),
                txCompName.getText(),
                txCompModel.getText(),
                txCompSn.getText(),
                cbType.getSelectedIndex(),
                txCompMarca.getText(),
                Double.parseDouble(txPrice.getText())
        );*/
        
        /*components.add(vo);*/
        
        JOptionPane.showMessageDialog(null,"Função está em fase de teste!","Atenção", JOptionPane.OK_OPTION);
        /*int codigo = (int) RandomId.generateRandomId(000000, 999999);
        if(exc.createExcelFile(components)){
        JOptionPane.showMessageDialog(null,"Dados cadastrados com sucesso","Sucesso", JOptionPane.OK_OPTION);
        }
        txComponent.setText(Integer.toString(codigo));*/
        
    }//GEN-LAST:event_btnExcelActionPerformed

    private String returnPath(String format){
        Date currentDate = new Date();
        String fileNameBase = ConvertDateToStringUtil.convertToString(currentDate);
        String filePathBase = "C:\\Users\\lukas\\Desktop\\"+fileNameBase+"."+format;
        return filePathBase;
    }
  
    private void fillJCombo() throws SQLException{
        Connection conn;
        conn = MyConnection.getConnection();
        type = new TypeVo();
        tDao = new TypeDao();
        
        List<TypeVo> types = tDao.carregaDados();
        DefaultComboBoxModel cbModel = (DefaultComboBoxModel) cbType.getModel();
        cbModel.removeAllElements();
        if(conn != null && !types.isEmpty()){
            for(TypeVo t: types){
                cbType.addItem(t);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Os dados da combo não podem ser carregados pois não há conexão"
                    + "\n Os dados serão carregados estaticamente.", "Atenção", JOptionPane.OK_OPTION);
            fillJComboStatic();
        }
        
        
    }
    
    private void fillJComboStatic(){
        TypeVo type = new TypeVo(); 
        DefaultComboBoxModel cbModel = (DefaultComboBoxModel) cbType.getModel();
        cbModel.removeAllElements();
        for(String types : type.getStaticTypes()){
            cbType.addItem(types);
        }
        
    }
    
    private void rdTxTStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdTxTStateChanged
        if(this.rdTxT.isSelected()){
            txFilePath.setText(returnPath("txt"));
            btnSalvarTxt.setEnabled(true);
        } else {
            txFilePath.setText("");
            btnSalvarTxt.setEnabled(false);
        }
    }//GEN-LAST:event_rdTxTStateChanged

    private void btnSalvarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTxtActionPerformed
        ComponentVo vo = new ComponentVo();
        
        int cdComponent = Integer.parseInt(txComponent.getText());
        String name = txCompName.getText();
        String model = txCompModel.getText();
        String serial = txCompSn.getText();
        String manuf =  txCompMarca.getText();
        Double preco = Double.parseDouble(txPrice.getText());
        String type = cbType.getSelectedItem().toString();
        
        vo.setIdComponent(cdComponent);
        vo.setName(name);
        vo.setModel(model);
        vo.setSerialNumber(serial);
        vo.getType().setType(type);
        vo.setManufacturer(manuf);
        vo.setPrice(preco);
        
        
        String path = txFilePath.getText();
        FileTxt txt = new FileTxt(vo, path);
       
        int codigo = (int) RandomIdUtil.generateRandomId(000000, 999999);
        if(txt.salvarDados()){
            JOptionPane.showMessageDialog(null,"Dados cadastrados com sucesso","Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
        txComponent.setText(Integer.toString(codigo));
    }//GEN-LAST:event_btnSalvarTxtActionPerformed

    private void cbTypeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbTypeAncestorAdded
        try {
            fillJCombo();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbTypeAncestorAdded

    private void btnSalvarBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarBdActionPerformed
        ComponentDao dao = new ComponentDao();
        
        ComponentVo component = new ComponentVo();
        TypeVo t = new TypeVo();
        
        int codigo = Integer.parseInt(txComponent.getText());
        String nome = txCompName.getText();
        String modelo = txCompModel.getText();
        String serial = txCompSn.getText();
        String marca = txCompMarca.getText();
        Double preco = Double.parseDouble(txPrice.getText());
        String type = cbType.getSelectedItem().toString();
        
        String[] campos = {nome, modelo, serial, marca, preco.toString()};
        
        for(String campo : campos){
            if(campo.isEmpty() && campo == null ){
                JOptionPane.showMessageDialog(null, "Campo " + campo + " deve ser preenchido", "Erro", JOptionPane.OK_OPTION);
            } else {
                component.setName(nome);
                component.setModel(modelo);
                component.setSerialNumber(serial);
                //component.setType(type);
                component.setManufacturer(marca);
                component.setPrice(preco);
                try {
                    if(dao.salvar(component)){
                        JOptionPane.showMessageDialog(null, "Sucesso ao inserir dados", "Sucesso", JOptionPane.OK_OPTION);
                    }
                } catch (SQLException ex) {
                   ex.getMessage();
                } 
            }
        }
    }//GEN-LAST:event_btnSalvarBdActionPerformed

    private void btTelaDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTelaDadosActionPerformed
        TelaCatalogo catalogo = new TelaCatalogo();
        catalogo.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_btTelaDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTelaDados;
    private javax.swing.JButton btnExcel;
    private javax.swing.ButtonGroup btnRdGroup;
    private javax.swing.JButton btnSalvarBd;
    private javax.swing.JButton btnSalvarTxt;
    private javax.swing.JComboBox cbType;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdBd;
    private javax.swing.JRadioButton rdExcel;
    private javax.swing.JRadioButton rdTxT;
    private javax.swing.JTextField txCompMarca;
    private javax.swing.JTextField txCompModel;
    private javax.swing.JTextField txCompName;
    private javax.swing.JTextField txCompSn;
    private javax.swing.JTextField txComponent;
    private javax.swing.JTextField txFilePath;
    private javax.swing.JTextField txPrice;
    // End of variables declaration//GEN-END:variables
}
